version: "3"
services:
  api:
    build: ./app
    depends_on:
      - postgres-service
    volumes:
      - ./:/home/node/api
    ports:
      - 3000:3000
    command: ["sleep", "infinity"]
    networks:
      default:
        aliases:
          - api-service
  # 開発用DB
  postgres-service:
    image: takeshi1215/postgres16:v1.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: crawler
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  # テスト用DB
  db_test:
    image: takeshi1215/postgres16:v1.1
    ports:
      - 4321:5432
    environment:
      POSTGRES_DB: crawler
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
networks:
  default:
    name: crawler_dev_net
