#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	CREATE DATABASE $DB_NAME TEMPLATE='template0' ENCODING='UTF8' LC_CTYPE='ja_JP.UTF-8' LC_COLLATE='ja_JP.UTF-8';
	\c $DB_NAME;
	
	REVOKE CREATE ON SCHEMA public FROM PUBLIC;
	REVOKE ALL ON DATABASE $DB_NAME FROM PUBLIC;
	
	CREATE ROLE readwrite;
	CREATE SCHEMA crawler_schema;
	GRANT CONNECT ON DATABASE $DB_NAME TO readwrite;
	GRANT USAGE, CREATE ON SCHEMA crawler_schema TO readwrite;
	GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA crawler_schema TO readwrite;
	ALTER DEFAULT PRIVILEGES IN SCHEMA crawler_schema GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO readwrite;
	GRANT USAGE ON ALL SEQUENCES IN SCHEMA crawler_schema TO readwrite;
	ALTER DEFAULT PRIVILEGES IN SCHEMA crawler_schema GRANT USAGE ON SEQUENCES TO readwrite;
	
	CREATE USER $USER_NAME WITH PASSWORD '$USER_PASSWORD';
	GRANT readwrite TO $USER_NAME;
EOSQL